// ARCHIVO GENERADO desde prisma/schema.sql — no editar a mano.
// Regenerar tras cambiar prisma/schema.prisma (ver comentario en prisma/schema.sql).

export const SCHEMA_TABLES: string[] = [
  "products",
  "categories",
  "brands",
  "clients",
  "sales",
  "sale_items",
  "settings",
  "devolutions",
  "devolution_items",
  "licenses",
  "CashClosing",
  "users",
  "role_configs",
  "suppliers",
  "purchases",
  "combo_items",
  "purchase_items",
  "credit_payments",
  "inventory_movements",
  "held_sales",
  "held_sale_items",
  "quotes",
  "quote_items",
  "delivery_notes",
  "delivery_note_items",
  "expense_categories",
  "expenses",
];

export const CREATE_TABLE_STATEMENTS: string[] = [
  "CREATE TABLE IF NOT EXISTS \"products\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"name\" TEXT NOT NULL, \"description\" TEXT NOT NULL DEFAULT '', \"barcode\" TEXT NOT NULL DEFAULT '', \"secondaryBarcode\" TEXT NOT NULL DEFAULT '', \"price\" REAL NOT NULL, \"cost\" REAL NOT NULL DEFAULT 0, \"marginPercent\" REAL NOT NULL DEFAULT 0, \"taxType\" TEXT NOT NULL DEFAULT 'general', \"stock\" REAL NOT NULL DEFAULT 0, \"minStock\" REAL NOT NULL DEFAULT 5, \"icon\" TEXT NOT NULL DEFAULT '', \"image\" TEXT NOT NULL DEFAULT '', \"wholesalePrice\" REAL NOT NULL DEFAULT 0, \"wholesaleCost\" REAL NOT NULL DEFAULT 0, \"wholesaleMarginPercent\" REAL NOT NULL DEFAULT 0, \"minWholesaleQty\" INTEGER NOT NULL DEFAULT 0, \"noStock\" BOOLEAN NOT NULL DEFAULT false, \"vendePorPeso\" BOOLEAN NOT NULL DEFAULT false, \"unidadPeso\" TEXT NOT NULL DEFAULT '', \"location\" TEXT NOT NULL DEFAULT '', \"expirationDate\" DATETIME, \"lotNumber\" TEXT NOT NULL DEFAULT '', \"isCombo\" BOOLEAN NOT NULL DEFAULT false, \"loyaltyPoints\" INTEGER NOT NULL DEFAULT 0, \"unitsPerBox\" INTEGER NOT NULL DEFAULT 0, \"boxPrice\" REAL NOT NULL DEFAULT 0, \"boxMarginPercent\" REAL NOT NULL DEFAULT 0, \"granMayorPrice\" REAL NOT NULL DEFAULT 0, \"isGranMayor\" BOOLEAN NOT NULL DEFAULT false, \"categoryId\" TEXT, \"brandId\" TEXT, \"active\" BOOLEAN NOT NULL DEFAULT true, \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL, CONSTRAINT \"products_categoryId_fkey\" FOREIGN KEY (\"categoryId\") REFERENCES \"categories\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT \"products_brandId_fkey\" FOREIGN KEY (\"brandId\") REFERENCES \"brands\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"categories\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"name\" TEXT NOT NULL, \"icon\" TEXT NOT NULL DEFAULT '', \"color\" TEXT NOT NULL DEFAULT '#6366f1', \"active\" BOOLEAN NOT NULL DEFAULT true )",
  "CREATE TABLE IF NOT EXISTS \"brands\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"name\" TEXT NOT NULL, \"active\" BOOLEAN NOT NULL DEFAULT true )",
  "CREATE TABLE IF NOT EXISTS \"clients\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"type\" TEXT NOT NULL DEFAULT 'natural', \"docType\" TEXT NOT NULL DEFAULT 'V', \"docNumber\" TEXT NOT NULL, \"fullName\" TEXT NOT NULL, \"firstName\" TEXT NOT NULL DEFAULT '', \"lastName\" TEXT NOT NULL DEFAULT '', \"businessName\" TEXT NOT NULL DEFAULT '', \"phone\" TEXT NOT NULL DEFAULT '', \"email\" TEXT NOT NULL DEFAULT '', \"address\" TEXT NOT NULL DEFAULT '', \"taxInfo\" TEXT NOT NULL DEFAULT '', \"isFinalClient\" BOOLEAN NOT NULL DEFAULT false, \"creditBalance\" REAL NOT NULL DEFAULT 0, \"creditLimit\" REAL NOT NULL DEFAULT 0, \"isActive\" BOOLEAN NOT NULL DEFAULT true, \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL )",
  "CREATE TABLE IF NOT EXISTS \"sales\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"date\" DATETIME NOT NULL, \"subtotal\" REAL NOT NULL, \"taxAmount\" REAL NOT NULL DEFAULT 0, \"discount\" REAL NOT NULL DEFAULT 0, \"total\" REAL NOT NULL, \"totalBs\" REAL NOT NULL, \"exchangeRate\" REAL NOT NULL, \"paymentMethod\" TEXT NOT NULL DEFAULT 'efectivo', \"referenceNumber\" TEXT NOT NULL DEFAULT '', \"mixedPaymentJson\" TEXT NOT NULL DEFAULT '', \"customerName\" TEXT NOT NULL DEFAULT '', \"clientDocType\" TEXT NOT NULL DEFAULT '', \"clientDocNumber\" TEXT NOT NULL DEFAULT '', \"clientName\" TEXT NOT NULL DEFAULT '', \"clientAddress\" TEXT NOT NULL DEFAULT '', \"sellerName\" TEXT NOT NULL DEFAULT '', \"sellerRole\" TEXT NOT NULL DEFAULT '', \"isCredit\" BOOLEAN NOT NULL DEFAULT false, \"creditPaid\" REAL NOT NULL DEFAULT 0, \"creditDays\" INTEGER NOT NULL DEFAULT 30, \"creditDueDate\" DATETIME, \"notes\" TEXT NOT NULL DEFAULT '', \"invoiceNumber\" TEXT NOT NULL, \"clientId\" TEXT, \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT \"sales_clientId_fkey\" FOREIGN KEY (\"clientId\") REFERENCES \"clients\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"sale_items\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"saleId\" TEXT NOT NULL, \"productId\" TEXT NOT NULL, \"quantity\" REAL NOT NULL, \"unitPrice\" REAL NOT NULL, \"total\" REAL NOT NULL, CONSTRAINT \"sale_items_productId_fkey\" FOREIGN KEY (\"productId\") REFERENCES \"products\" (\"id\") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT \"sale_items_saleId_fkey\" FOREIGN KEY (\"saleId\") REFERENCES \"sales\" (\"id\") ON DELETE CASCADE ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"settings\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"storeName\" TEXT NOT NULL DEFAULT 'Mi Tienda', \"storeAddress\" TEXT NOT NULL DEFAULT '', \"storePhone\" TEXT NOT NULL DEFAULT '', \"storeRif\" TEXT NOT NULL DEFAULT '', \"bcvRate\" REAL NOT NULL DEFAULT 36.50, \"taxRate\" REAL NOT NULL DEFAULT 0, \"currency\" TEXT NOT NULL DEFAULT 'USD', \"allowZeroStock\" BOOLEAN NOT NULL DEFAULT false, \"enableDiscount\" BOOLEAN NOT NULL DEFAULT false, \"maxDiscountPct\" INTEGER NOT NULL DEFAULT 20, \"theme\" TEXT NOT NULL DEFAULT 'blue', \"ticketFontSize\" INTEGER NOT NULL DEFAULT 8, \"ticketFontFamily\" TEXT NOT NULL DEFAULT 'monospace', \"ticketHeaderMsg\" TEXT NOT NULL DEFAULT '', \"ticketFooterMsg\" TEXT NOT NULL DEFAULT 'Gracias por su compra!', \"ticketShowPhone\" BOOLEAN NOT NULL DEFAULT true, \"ticketShowSeller\" BOOLEAN NOT NULL DEFAULT true, \"ticketShowExchange\" BOOLEAN NOT NULL DEFAULT true, \"ticketCurrencyMode\" TEXT NOT NULL DEFAULT 'dual', \"ticketShowSlogan\" BOOLEAN NOT NULL DEFAULT false, \"ticketBold\" BOOLEAN NOT NULL DEFAULT true, \"ticketPaperWidth\" TEXT NOT NULL DEFAULT '58mm', \"ticketMarginLeft\" REAL NOT NULL DEFAULT 0, \"ticketMarginRight\" REAL NOT NULL DEFAULT 0, \"ticketUseAgent\" BOOLEAN NOT NULL DEFAULT true, \"ticketAgentUrl\" TEXT NOT NULL DEFAULT 'http://localhost:9100', \"ticketShowCashReceived\" BOOLEAN NOT NULL DEFAULT true, \"ticketShowLogo\" BOOLEAN NOT NULL DEFAULT true, \"storeLogo\" TEXT NOT NULL DEFAULT '', \"businessType\" TEXT NOT NULL DEFAULT 'general', \"taxMode\" TEXT NOT NULL DEFAULT 'included', \"themeMode\" TEXT NOT NULL DEFAULT 'light', \"euroUsdtRate\" REAL NOT NULL DEFAULT 0, \"promoActive\" BOOLEAN NOT NULL DEFAULT true, \"promoLabel\" TEXT NOT NULL DEFAULT 'PRECIO EXCLUSIVO', \"promoOldPrice\" REAL NOT NULL DEFAULT 280, \"promoCurrentPrice\" REAL NOT NULL DEFAULT 180, \"promoExpiryDate\" TEXT NOT NULL DEFAULT '', \"updatedAt\" DATETIME NOT NULL )",
  "CREATE TABLE IF NOT EXISTS \"devolutions\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"saleId\" TEXT NOT NULL, \"date\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"reason\" TEXT NOT NULL, \"totalUsd\" REAL NOT NULL, \"totalBs\" REAL NOT NULL, \"exchangeRate\" REAL NOT NULL, \"status\" TEXT NOT NULL DEFAULT 'completada', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT \"devolutions_saleId_fkey\" FOREIGN KEY (\"saleId\") REFERENCES \"sales\" (\"id\") ON DELETE RESTRICT ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"devolution_items\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"devolutionId\" TEXT NOT NULL, \"productId\" TEXT NOT NULL, \"productName\" TEXT NOT NULL, \"quantity\" REAL NOT NULL, \"unitPrice\" REAL NOT NULL, \"total\" REAL NOT NULL, CONSTRAINT \"devolution_items_productId_fkey\" FOREIGN KEY (\"productId\") REFERENCES \"products\" (\"id\") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT \"devolution_items_devolutionId_fkey\" FOREIGN KEY (\"devolutionId\") REFERENCES \"devolutions\" (\"id\") ON DELETE CASCADE ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"licenses\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"machineId\" TEXT NOT NULL, \"licenseKey\" TEXT NOT NULL DEFAULT '', \"licenseType\" TEXT NOT NULL DEFAULT 'trial', \"activatedAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"expiresAt\" DATETIME NOT NULL, \"maxProducts\" INTEGER NOT NULL DEFAULT 30, \"maxDailySales\" INTEGER NOT NULL DEFAULT 15, \"maxUsers\" INTEGER NOT NULL DEFAULT 1, \"isActive\" BOOLEAN NOT NULL DEFAULT true, \"maxActivations\" INTEGER NOT NULL DEFAULT 1, \"activationCount\" INTEGER NOT NULL DEFAULT 1, \"previousMachines\" TEXT NOT NULL DEFAULT '', \"blockedReason\" TEXT NOT NULL DEFAULT '', \"ownerName\" TEXT NOT NULL DEFAULT '', \"ownerEmail\" TEXT NOT NULL DEFAULT '', \"ownerPhone\" TEXT NOT NULL DEFAULT '', \"ownerRif\" TEXT NOT NULL DEFAULT '', \"notes\" TEXT NOT NULL DEFAULT '', \"updatedAt\" DATETIME NOT NULL )",
  "CREATE TABLE IF NOT EXISTS \"CashClosing\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"date\" DATETIME NOT NULL, \"closingType\" TEXT NOT NULL DEFAULT 'final', \"sellerName\" TEXT NOT NULL DEFAULT '', \"sellerRole\" TEXT NOT NULL DEFAULT '', \"totalSalesUsd\" REAL NOT NULL DEFAULT 0, \"totalSalesBs\" REAL NOT NULL DEFAULT 0, \"totalReturnsUsd\" REAL NOT NULL DEFAULT 0, \"totalReturnsBs\" REAL NOT NULL DEFAULT 0, \"netTotalUsd\" REAL NOT NULL DEFAULT 0, \"netTotalBs\" REAL NOT NULL DEFAULT 0, \"salesCount\" INTEGER NOT NULL DEFAULT 0, \"returnsCount\" INTEGER NOT NULL DEFAULT 0, \"cashUsd\" REAL NOT NULL DEFAULT 0, \"cashBs\" REAL NOT NULL DEFAULT 0, \"cardUsd\" REAL NOT NULL DEFAULT 0, \"cardBs\" REAL NOT NULL DEFAULT 0, \"checkUsd\" REAL NOT NULL DEFAULT 0, \"checkBs\" REAL NOT NULL DEFAULT 0, \"transferUsd\" REAL NOT NULL DEFAULT 0, \"transferBs\" REAL NOT NULL DEFAULT 0, \"mobileUsd\" REAL NOT NULL DEFAULT 0, \"mobileBs\" REAL NOT NULL DEFAULT 0, \"efectivoUsdUsd\" REAL NOT NULL DEFAULT 0, \"efectivoUsdBs\" REAL NOT NULL DEFAULT 0, \"creditSalesUsd\" REAL NOT NULL DEFAULT 0, \"creditSalesBs\" REAL NOT NULL DEFAULT 0, \"creditSalesCount\" INTEGER NOT NULL DEFAULT 0, \"casheaSalesUsd\" REAL NOT NULL DEFAULT 0, \"casheaSalesBs\" REAL NOT NULL DEFAULT 0, \"casheaSalesCount\" INTEGER NOT NULL DEFAULT 0, \"zelleUsd\" REAL NOT NULL DEFAULT 0, \"zelleBs\" REAL NOT NULL DEFAULT 0, \"usdtUsd\" REAL NOT NULL DEFAULT 0, \"usdtBs\" REAL NOT NULL DEFAULT 0, \"breakdownJson\" TEXT NOT NULL DEFAULT '{}', \"exchangeRate\" REAL NOT NULL DEFAULT 0, \"observations\" TEXT NOT NULL DEFAULT '', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP )",
  "CREATE TABLE IF NOT EXISTS \"users\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"username\" TEXT NOT NULL, \"password\" TEXT NOT NULL, \"fullName\" TEXT NOT NULL DEFAULT '', \"role\" TEXT NOT NULL DEFAULT 'cajero', \"isActive\" BOOLEAN NOT NULL DEFAULT true, \"permissions\" TEXT NOT NULL DEFAULT '', \"avatar\" TEXT NOT NULL DEFAULT '', \"lastLogin\" DATETIME, \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL )",
  "CREATE TABLE IF NOT EXISTS \"role_configs\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"roleName\" TEXT NOT NULL, \"label\" TEXT NOT NULL DEFAULT '', \"permissions\" TEXT NOT NULL DEFAULT '{}', \"color\" TEXT NOT NULL DEFAULT '#6366f1', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL )",
  "CREATE TABLE IF NOT EXISTS \"suppliers\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"name\" TEXT NOT NULL, \"rif\" TEXT NOT NULL DEFAULT '', \"phone\" TEXT NOT NULL DEFAULT '', \"email\" TEXT NOT NULL DEFAULT '', \"address\" TEXT NOT NULL DEFAULT '', \"contact\" TEXT NOT NULL DEFAULT '', \"notes\" TEXT NOT NULL DEFAULT '', \"isActive\" BOOLEAN NOT NULL DEFAULT true, \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL )",
  "CREATE TABLE IF NOT EXISTS \"purchases\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"date\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"number\" TEXT NOT NULL DEFAULT '', \"supplierId\" TEXT, \"totalUsd\" REAL NOT NULL DEFAULT 0, \"totalBs\" REAL NOT NULL DEFAULT 0, \"exchangeRate\" REAL NOT NULL DEFAULT 0, \"notes\" TEXT NOT NULL DEFAULT '', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL, CONSTRAINT \"purchases_supplierId_fkey\" FOREIGN KEY (\"supplierId\") REFERENCES \"suppliers\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"combo_items\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"comboId\" TEXT NOT NULL, \"productId\" TEXT NOT NULL, \"quantity\" INTEGER NOT NULL DEFAULT 1, CONSTRAINT \"combo_items_comboId_fkey\" FOREIGN KEY (\"comboId\") REFERENCES \"products\" (\"id\") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT \"combo_items_productId_fkey\" FOREIGN KEY (\"productId\") REFERENCES \"products\" (\"id\") ON DELETE RESTRICT ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"purchase_items\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"purchaseId\" TEXT NOT NULL, \"productId\" TEXT, \"productName\" TEXT NOT NULL DEFAULT '', \"quantity\" REAL NOT NULL, \"unitCost\" REAL NOT NULL, \"total\" REAL NOT NULL, \"isBox\" BOOLEAN NOT NULL DEFAULT false, \"unitsPerBox\" REAL NOT NULL DEFAULT 0, \"boxQty\" REAL NOT NULL DEFAULT 0, \"boxCost\" REAL NOT NULL DEFAULT 0, \"calcUnitCost\" REAL NOT NULL DEFAULT 0, \"calcMargin\" REAL NOT NULL DEFAULT 0, \"calcPrice\" REAL NOT NULL DEFAULT 0, \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT \"purchase_items_productId_fkey\" FOREIGN KEY (\"productId\") REFERENCES \"products\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT \"purchase_items_purchaseId_fkey\" FOREIGN KEY (\"purchaseId\") REFERENCES \"purchases\" (\"id\") ON DELETE CASCADE ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"credit_payments\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"saleId\" TEXT NOT NULL, \"clientId\" TEXT, \"date\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"amount\" REAL NOT NULL, \"exchangeRate\" REAL NOT NULL, \"amountBs\" REAL NOT NULL, \"method\" TEXT NOT NULL DEFAULT 'efectivo', \"reference\" TEXT NOT NULL DEFAULT '', \"notes\" TEXT NOT NULL DEFAULT '', \"createdBy\" TEXT NOT NULL DEFAULT '', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT \"credit_payments_saleId_fkey\" FOREIGN KEY (\"saleId\") REFERENCES \"sales\" (\"id\") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT \"credit_payments_clientId_fkey\" FOREIGN KEY (\"clientId\") REFERENCES \"clients\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"inventory_movements\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"productId\" TEXT NOT NULL, \"date\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"movementType\" TEXT NOT NULL, \"concept\" TEXT NOT NULL DEFAULT '', \"quantity\" REAL NOT NULL, \"absQuantity\" REAL NOT NULL, \"unitCost\" REAL NOT NULL DEFAULT 0, \"totalCost\" REAL NOT NULL DEFAULT 0, \"balanceQty\" REAL NOT NULL DEFAULT 0, \"balanceTotalCost\" REAL NOT NULL DEFAULT 0, \"balanceAvgCost\" REAL NOT NULL DEFAULT 0, \"userId\" TEXT NOT NULL DEFAULT '', \"userName\" TEXT NOT NULL DEFAULT '', \"userRole\" TEXT NOT NULL DEFAULT '', \"referenceId\" TEXT NOT NULL DEFAULT '', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT \"inventory_movements_productId_fkey\" FOREIGN KEY (\"productId\") REFERENCES \"products\" (\"id\") ON DELETE RESTRICT ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"held_sales\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"number\" INTEGER NOT NULL DEFAULT 0, \"userId\" TEXT NOT NULL DEFAULT '', \"userName\" TEXT NOT NULL DEFAULT '', \"clientName\" TEXT NOT NULL DEFAULT '', \"clientId\" TEXT, \"subtotal\" REAL NOT NULL DEFAULT 0, \"taxAmount\" REAL NOT NULL DEFAULT 0, \"discount\" REAL NOT NULL DEFAULT 0, \"total\" REAL NOT NULL DEFAULT 0, \"totalBs\" REAL NOT NULL DEFAULT 0, \"exchangeRate\" REAL NOT NULL DEFAULT 0, \"paymentMethod\" TEXT NOT NULL DEFAULT 'efectivo', \"notes\" TEXT NOT NULL DEFAULT '', \"status\" TEXT NOT NULL DEFAULT 'espera', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL, CONSTRAINT \"held_sales_clientId_fkey\" FOREIGN KEY (\"clientId\") REFERENCES \"clients\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"held_sale_items\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"heldSaleId\" TEXT NOT NULL, \"productId\" TEXT NOT NULL, \"productName\" TEXT NOT NULL DEFAULT '', \"quantity\" REAL NOT NULL, \"unitPrice\" REAL NOT NULL, \"total\" REAL NOT NULL, \"taxType\" TEXT NOT NULL DEFAULT 'general', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT \"held_sale_items_heldSaleId_fkey\" FOREIGN KEY (\"heldSaleId\") REFERENCES \"held_sales\" (\"id\") ON DELETE CASCADE ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"quotes\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"number\" INTEGER NOT NULL DEFAULT 0, \"userId\" TEXT NOT NULL DEFAULT '', \"userName\" TEXT NOT NULL DEFAULT '', \"clientName\" TEXT NOT NULL DEFAULT '', \"clientId\" TEXT, \"subtotal\" REAL NOT NULL DEFAULT 0, \"taxAmount\" REAL NOT NULL DEFAULT 0, \"discount\" REAL NOT NULL DEFAULT 0, \"total\" REAL NOT NULL DEFAULT 0, \"totalBs\" REAL NOT NULL DEFAULT 0, \"exchangeRate\" REAL NOT NULL DEFAULT 0, \"notes\" TEXT NOT NULL DEFAULT '', \"validUntil\" TEXT NOT NULL DEFAULT '', \"status\" TEXT NOT NULL DEFAULT 'pendiente', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL, CONSTRAINT \"quotes_clientId_fkey\" FOREIGN KEY (\"clientId\") REFERENCES \"clients\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"quote_items\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"quoteId\" TEXT NOT NULL, \"productId\" TEXT NOT NULL, \"productName\" TEXT NOT NULL DEFAULT '', \"quantity\" REAL NOT NULL, \"unitPrice\" REAL NOT NULL, \"total\" REAL NOT NULL, \"taxType\" TEXT NOT NULL DEFAULT 'general', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT \"quote_items_quoteId_fkey\" FOREIGN KEY (\"quoteId\") REFERENCES \"quotes\" (\"id\") ON DELETE CASCADE ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"delivery_notes\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"number\" INTEGER NOT NULL DEFAULT 0, \"userId\" TEXT NOT NULL DEFAULT '', \"userName\" TEXT NOT NULL DEFAULT '', \"recipientName\" TEXT NOT NULL DEFAULT '', \"recipientDoc\" TEXT NOT NULL DEFAULT '', \"recipientAddr\" TEXT NOT NULL DEFAULT '', \"reason\" TEXT NOT NULL DEFAULT '', \"notes\" TEXT NOT NULL DEFAULT '', \"totalUsd\" REAL NOT NULL DEFAULT 0, \"totalBs\" REAL NOT NULL DEFAULT 0, \"exchangeRate\" REAL NOT NULL DEFAULT 0, \"status\" TEXT NOT NULL DEFAULT 'emitida', \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL )",
  "CREATE TABLE IF NOT EXISTS \"delivery_note_items\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"deliveryNoteId\" TEXT NOT NULL, \"productId\" TEXT NOT NULL, \"productName\" TEXT NOT NULL DEFAULT '', \"quantity\" REAL NOT NULL, \"unitCost\" REAL NOT NULL DEFAULT 0, \"totalCost\" REAL NOT NULL DEFAULT 0, \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT \"delivery_note_items_deliveryNoteId_fkey\" FOREIGN KEY (\"deliveryNoteId\") REFERENCES \"delivery_notes\" (\"id\") ON DELETE CASCADE ON UPDATE CASCADE )",
  "CREATE TABLE IF NOT EXISTS \"expense_categories\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"name\" TEXT NOT NULL, \"description\" TEXT NOT NULL DEFAULT '', \"icon\" TEXT NOT NULL DEFAULT 'receipt', \"color\" TEXT NOT NULL DEFAULT '#ef4444', \"active\" BOOLEAN NOT NULL DEFAULT true, \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL )",
  "CREATE TABLE IF NOT EXISTS \"expenses\" ( \"id\" TEXT NOT NULL PRIMARY KEY, \"tenant_id\" TEXT NOT NULL DEFAULT 'default', \"categoryId\" TEXT NOT NULL, \"description\" TEXT NOT NULL, \"amount\" REAL NOT NULL, \"amountBs\" REAL NOT NULL DEFAULT 0, \"exchangeRate\" REAL NOT NULL DEFAULT 0, \"date\" DATETIME NOT NULL, \"paymentMethod\" TEXT NOT NULL DEFAULT 'efectivo', \"reference\" TEXT NOT NULL DEFAULT '', \"notes\" TEXT NOT NULL DEFAULT '', \"userId\" TEXT, \"createdAt\" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, \"updatedAt\" DATETIME NOT NULL, CONSTRAINT \"expenses_categoryId_fkey\" FOREIGN KEY (\"categoryId\") REFERENCES \"expense_categories\" (\"id\") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT \"expenses_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES \"users\" (\"id\") ON DELETE SET NULL ON UPDATE CASCADE )",
];

export const DROP_LEGACY_UNIQUE_INDEXES: string[] = [
  "DROP INDEX IF EXISTS \"categories_name_key\"",
  "DROP INDEX IF EXISTS \"Category_name_key\"",
  "DROP INDEX IF EXISTS \"brands_name_key\"",
  "DROP INDEX IF EXISTS \"Brand_name_key\"",
  "DROP INDEX IF EXISTS \"clients_docNumber_key\"",
  "DROP INDEX IF EXISTS \"Client_docNumber_key\"",
  "DROP INDEX IF EXISTS \"sales_invoiceNumber_key\"",
  "DROP INDEX IF EXISTS \"Sale_invoiceNumber_key\"",
  "DROP INDEX IF EXISTS \"licenses_machineId_key\"",
  "DROP INDEX IF EXISTS \"License_machineId_key\"",
  "DROP INDEX IF EXISTS \"users_username_key\"",
  "DROP INDEX IF EXISTS \"User_username_key\"",
  "DROP INDEX IF EXISTS \"role_configs_roleName_key\"",
  "DROP INDEX IF EXISTS \"RoleConfig_roleName_key\"",
  "DROP INDEX IF EXISTS \"expense_categories_name_key\"",
  "DROP INDEX IF EXISTS \"ExpenseCategory_name_key\"",
];

export const CREATE_INDEX_STATEMENTS: string[] = [
  "CREATE INDEX IF NOT EXISTS \"products_tenant_id_idx\" ON \"products\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"categories_tenant_id_idx\" ON \"categories\"(\"tenant_id\")",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"categories_tenant_id_name_key\" ON \"categories\"(\"tenant_id\", \"name\")",
  "CREATE INDEX IF NOT EXISTS \"brands_tenant_id_idx\" ON \"brands\"(\"tenant_id\")",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"brands_tenant_id_name_key\" ON \"brands\"(\"tenant_id\", \"name\")",
  "CREATE INDEX IF NOT EXISTS \"clients_docNumber_idx\" ON \"clients\"(\"docNumber\")",
  "CREATE INDEX IF NOT EXISTS \"clients_fullName_idx\" ON \"clients\"(\"fullName\")",
  "CREATE INDEX IF NOT EXISTS \"clients_type_idx\" ON \"clients\"(\"type\")",
  "CREATE INDEX IF NOT EXISTS \"clients_tenant_id_idx\" ON \"clients\"(\"tenant_id\")",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"clients_tenant_id_docNumber_key\" ON \"clients\"(\"tenant_id\", \"docNumber\")",
  "CREATE INDEX IF NOT EXISTS \"sales_date_idx\" ON \"sales\"(\"date\")",
  "CREATE INDEX IF NOT EXISTS \"sales_clientId_idx\" ON \"sales\"(\"clientId\")",
  "CREATE INDEX IF NOT EXISTS \"sales_tenant_id_idx\" ON \"sales\"(\"tenant_id\")",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"sales_tenant_id_invoiceNumber_key\" ON \"sales\"(\"tenant_id\", \"invoiceNumber\")",
  "CREATE INDEX IF NOT EXISTS \"sale_items_tenant_id_idx\" ON \"sale_items\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"settings_tenant_id_idx\" ON \"settings\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"devolutions_date_idx\" ON \"devolutions\"(\"date\")",
  "CREATE INDEX IF NOT EXISTS \"devolutions_saleId_idx\" ON \"devolutions\"(\"saleId\")",
  "CREATE INDEX IF NOT EXISTS \"devolutions_tenant_id_idx\" ON \"devolutions\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"devolution_items_tenant_id_idx\" ON \"devolution_items\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"licenses_tenant_id_idx\" ON \"licenses\"(\"tenant_id\")",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"licenses_tenant_id_machineId_key\" ON \"licenses\"(\"tenant_id\", \"machineId\")",
  "CREATE INDEX IF NOT EXISTS \"CashClosing_date_idx\" ON \"CashClosing\"(\"date\")",
  "CREATE INDEX IF NOT EXISTS \"users_tenant_id_idx\" ON \"users\"(\"tenant_id\")",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"users_tenant_id_username_key\" ON \"users\"(\"tenant_id\", \"username\")",
  "CREATE INDEX IF NOT EXISTS \"role_configs_tenant_id_idx\" ON \"role_configs\"(\"tenant_id\")",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"role_configs_tenant_id_roleName_key\" ON \"role_configs\"(\"tenant_id\", \"roleName\")",
  "CREATE INDEX IF NOT EXISTS \"suppliers_name_idx\" ON \"suppliers\"(\"name\")",
  "CREATE INDEX IF NOT EXISTS \"suppliers_tenant_id_idx\" ON \"suppliers\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"purchases_date_idx\" ON \"purchases\"(\"date\")",
  "CREATE INDEX IF NOT EXISTS \"purchases_supplierId_idx\" ON \"purchases\"(\"supplierId\")",
  "CREATE INDEX IF NOT EXISTS \"purchases_tenant_id_idx\" ON \"purchases\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"combo_items_tenant_id_idx\" ON \"combo_items\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"purchase_items_tenant_id_idx\" ON \"purchase_items\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"credit_payments_date_idx\" ON \"credit_payments\"(\"date\")",
  "CREATE INDEX IF NOT EXISTS \"credit_payments_saleId_idx\" ON \"credit_payments\"(\"saleId\")",
  "CREATE INDEX IF NOT EXISTS \"credit_payments_clientId_idx\" ON \"credit_payments\"(\"clientId\")",
  "CREATE INDEX IF NOT EXISTS \"credit_payments_tenant_id_idx\" ON \"credit_payments\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"inventory_movements_productId_idx\" ON \"inventory_movements\"(\"productId\")",
  "CREATE INDEX IF NOT EXISTS \"inventory_movements_date_idx\" ON \"inventory_movements\"(\"date\")",
  "CREATE INDEX IF NOT EXISTS \"inventory_movements_movementType_idx\" ON \"inventory_movements\"(\"movementType\")",
  "CREATE INDEX IF NOT EXISTS \"inventory_movements_tenant_id_idx\" ON \"inventory_movements\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"held_sales_userId_idx\" ON \"held_sales\"(\"userId\")",
  "CREATE INDEX IF NOT EXISTS \"held_sales_status_idx\" ON \"held_sales\"(\"status\")",
  "CREATE INDEX IF NOT EXISTS \"held_sales_tenant_id_idx\" ON \"held_sales\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"held_sale_items_tenant_id_idx\" ON \"held_sale_items\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"quotes_userId_idx\" ON \"quotes\"(\"userId\")",
  "CREATE INDEX IF NOT EXISTS \"quotes_status_idx\" ON \"quotes\"(\"status\")",
  "CREATE INDEX IF NOT EXISTS \"quotes_tenant_id_idx\" ON \"quotes\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"quote_items_tenant_id_idx\" ON \"quote_items\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"delivery_notes_userId_idx\" ON \"delivery_notes\"(\"userId\")",
  "CREATE INDEX IF NOT EXISTS \"delivery_notes_status_idx\" ON \"delivery_notes\"(\"status\")",
  "CREATE INDEX IF NOT EXISTS \"delivery_notes_createdAt_idx\" ON \"delivery_notes\"(\"createdAt\")",
  "CREATE INDEX IF NOT EXISTS \"delivery_notes_tenant_id_idx\" ON \"delivery_notes\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"delivery_note_items_tenant_id_idx\" ON \"delivery_note_items\"(\"tenant_id\")",
  "CREATE INDEX IF NOT EXISTS \"expense_categories_tenant_id_idx\" ON \"expense_categories\"(\"tenant_id\")",
  "CREATE UNIQUE INDEX IF NOT EXISTS \"expense_categories_tenant_id_name_key\" ON \"expense_categories\"(\"tenant_id\", \"name\")",
  "CREATE INDEX IF NOT EXISTS \"expenses_date_idx\" ON \"expenses\"(\"date\")",
  "CREATE INDEX IF NOT EXISTS \"expenses_categoryId_idx\" ON \"expenses\"(\"categoryId\")",
  "CREATE INDEX IF NOT EXISTS \"expenses_userId_idx\" ON \"expenses\"(\"userId\")",
  "CREATE INDEX IF NOT EXISTS \"expenses_tenant_id_idx\" ON \"expenses\"(\"tenant_id\")",
];
